const express = require("express");

const router = express.Router();

router.get("/", function (req, res, next) {
  res.json([
    { id: 17, country: "United Kingdom" },
    { id: 65, country: "Argentina" },
    { id: 30, country: "Australia" },
    { id: 32, country: "Austria" },
    { id: 22, country: "Bangladesh" },
    { id: 5, country: "Belgium" },
    { id: 51, country: "Bolivia" },
    { id: 8, country: "Brazil" },
    { id: 34, country: "Bulgaria" },
    { id: 80, country: "Burma" },
    { id: 73, country: "Cambodia" },
    { id: 61, country: "Canada" },
    { id: 56, country: "Chile" },
    { id: 7, country: "China" },
    { id: 81, country: "Costa Rica" },
    { id: 71, country: "Croatia" },
    { id: 64, country: "Cyprus" },
    { id: 62, country: "Czech Republic" },
    { id: 37, country: "Denmark" },
    { id: 77, country: "Dominican Republic" },
    { id: 48, country: "Egypt" },
    { id: 1, country: "England" },
    { id: 88, country: "Estonia" },
    { id: 68, country: "Finland" },
    { id: 6, country: "France" },
    { id: 59, country: "Gambia" },
    { id: 23, country: "Georgia" },
    { id: 9, country: "Germany" },
    { id: 14, country: "Ghana" },
    { id: 72, country: "Greece" },
    { id: 83, country: "Guyana" },
    { id: 74, country: "Holland" },
    { id: 21, country: "India" },
    { id: 46, country: "Indonesia" },
    { id: 36, country: "Iran" },
    { id: 35, country: "Israel" },
    { id: 20, country: "Italy" },
    { id: 63, country: "Ivory Coast" },
    { id: 89, country: "Jamaica" },
    { id: 78, country: "Japan" },
    { id: 76, country: "Kenya" },
    { id: 55, country: "Korea" },
    { id: 18, country: "Latvia" },
    { id: 24, country: "Lebanon" },
    { id: 49, country: "Lithuania" },
    { id: 86, country: "Luxembourg" },
    { id: 27, country: "Malawi" },
    { id: 47, country: "Malaysia" },
    { id: 41, country: "Maldives" },
    { id: 82, country: "Malta" },
    { id: 57, country: "Mexico" },
    { id: 38, country: "Morocco" },
    { id: 85, country: "Mozambique" },
    { id: 79, country: "Myanmar" },
    { id: 42, country: "New Zealand" },
    { id: 53, country: "Nigeria" },
    { id: 4, country: "Northern Ireland" },
    { id: 60, country: "Norway" },
    { id: 66, country: "Pakistan" },
    { id: 54, country: "Peru" },
    { id: 45, country: "Philippines" },
    { id: 50, country: "Poland" },
    { id: 70, country: "Portugal" },
    { id: 15, country: "Republic of Ireland" },
    { id: 40, country: "Romania" },
    { id: 26, country: "Russia" },
    { id: 31, country: "Saudi Arabia" },
    { id: 2, country: "Scotland" },
    { id: 69, country: "Sierra Leone" },
    { id: 84, country: "Slovenia" },
    { id: 52, country: "South Africa" },
    { id: 12, country: "South Korea" },
    { id: 19, country: "Spain" },
    { id: 75, country: "Sri Lanka" },
    { id: 58, country: "Suriname" },
    { id: 87, country: "Sweden" },
    { id: 28, country: "Switzerland" },
    { id: 33, country: "Syria" },
    { id: 39, country: "Taiwan" },
    { id: 16, country: "Thailand" },
    { id: 11, country: "The Netherlands" },
    { id: 67, country: "Tonga" },
    { id: 25, country: "Turkey" },
    { id: 44, country: "Uganda" },
    { id: 10, country: "USA" },
    { id: 29, country: "Vietnam" },
    { id: 3, country: "Wales" },
    { id: 13, country: "West Africa" },
    { id: 43, country: "Zimbabwe" },
  ]);
});

module.exports = router;
