name: pull_requests to dev trigger tests

on:
  pull_request:
    branches: [ dev ]

jobs:

  cypress:
    name: "checkout; launch docker-compose; execute cypress tests."
    runs-on: ubuntu-latest
    env:
      GOV_NOTIFY_API_KEY: ${{ secrets.DEV_GOV_NOTIFY_API_KEY }}
      NOTIFICATION_EMAIL: ${{ secrets.DEV_NOTIFICATION_EMAIL }}
      SESSION_KEY: ${{ secrets.DEV_SESSION_KEY }}
      CYPRESS_VIDEOS: ./test/cypress/videos

    steps:
    - uses: actions/checkout@v2
    - name: Start Docker Compose
      run: |
        docker-compose up -d
    - name: Run e2e tests
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      run: |
        pwd
        cd $GITHUB_WORKSPACE/test
        npm install
        npx cypress run

    - name: Archive video evidence
      if: ${{ always() }}
      uses: actions/upload-artifact@main
      with:
        name: videos
        path: ${{ env.CYPRESS_VIDEOS }}

  jest:
    name: "checkout; run jest."
    runs-on: ubuntu-latest
    env:
      GOV_NOTIFY_API_KEY: ${{ secrets.DEV_GOV_NOTIFY_API_KEY }}
      NOTIFICATION_EMAIL: ${{ secrets.DEV_NOTIFICATION_EMAIL }}
    steps:
    - uses: actions/checkout@v2
    - name: Run jest
      run: |
        pwd
        cd $GITHUB_WORKSPACE/incident-application-form
        npm install
        npm test
